# Ubuntu 14.04, ROOT > 6.08
sudo: false
dist: trusty

language: cpp

# install ROOT (already contain cmake > 3.0)
before_script:
    - wget https://root.cern.ch/download/root_v6.08.06.Linux-ubuntu14-x86_64-gcc4.8.tar.gz -O /tmp/root.v6.08.06.tar.gz
    - tar -xvf /tmp/root.v6.08.06.tar.gz
    - export PATH=$PATH:$PWD/root/bin:$HOME/bin
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/lib
    - export PYTHONPATH=$PYTHONPATH:$HOME/lib
    - source $PWD/root/bin/thisroot.sh

# command to run tests
script: 
    - mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=$HOME .. && make install && cd ..
    - fortythieves test/alibavadatatest.raw 
    - python test/skifftools_test.py -v

    
